//! UAX #31 identifier properties (`XID_Start` / `XID_Continue`),
//! M1a of the tier-D1 formula ladder (`goal_formula.md` §5.2).
//!
//! Why this module exists
//! ---------------------
//! Excel sheet names and defined names are not ASCII — `=Ω!Σ` and
//! `=ДАННЫЕ` are ordinary formulas — but Zig's stdlib ships no XID
//! tables, and `std.ascii.isAlphabetic` is the only predicate the
//! tokenizer had. The formula identifier grammar therefore needs its
//! own data, generated by `scripts/gen_unicode_tables.py --mode xid`
//! from a pinned Unicode 17 `DerivedCoreProperties.txt`.
//!
//! Lookup is a binary search over sorted, coalesced, non-overlapping
//! intervals: allocation-free, no global state, safe to call from any
//! thread. 691 + 806 ranges cost at most 10 probes each.
//!
//! Rooted at top-level `unicode/` for the same one-file-one-module-tree
//! reason as `nfc.zig` — see the comment above `nfc_mod` in `build.zig`.
//!
//! The tables are derived from the Unicode Character Database and used
//! under the Unicode License v3; see `THIRD_PARTY_NOTICES.md`.

const std = @import("std");
const tables = @import("tables/xid_data.zig");

/// The Unicode revision the committed tables were generated from.
/// `scripts/ci/check_unicode_tables.sh` re-derives them and fails on
/// any diff, so this is the version the tokenizer actually implements.
pub const unicode_version = tables.unicode_version;

/// True if `cp` may start a UAX #31 identifier.
///
/// Note this is `XID_Start` alone — the formula grammar's start set is
/// `XID_Start ∪ {_, \}` and lives in the tokenizer, which owns the
/// Excel-specific additions. Keeping them out of here means this module
/// stays a faithful mirror of the UCD.
pub fn isXidStart(cp: u21) bool {
    return inRanges(tables.xid_start, cp);
}

/// True if `cp` may continue a UAX #31 identifier. `XID_Continue` is a
/// superset of `XID_Start` (the generator asserts the containment) and
/// already includes `_`, digits, and combining marks.
pub fn isXidContinue(cp: u21) bool {
    return inRanges(tables.xid_continue, cp);
}

fn inRanges(ranges: []const tables.Range, cp: u21) bool {
    var lo: usize = 0;
    var hi: usize = ranges.len;
    while (lo < hi) {
        const mid = lo + (hi - lo) / 2;
        const r = ranges[mid];
        if (cp < r.lo) {
            hi = mid;
        } else if (cp > r.hi) {
            lo = mid + 1;
        } else {
            return true;
        }
    }
    return false;
}

// ─── tests ───────────────────────────────────────────────────────

const testing = std.testing;

test "table invariants: sorted, non-overlapping, coalesced, in range" {
    inline for (.{ tables.xid_start, tables.xid_continue }) |ranges| {
        try testing.expect(ranges.len > 0);
        var prev_hi: ?u21 = null;
        for (ranges) |r| {
            try testing.expect(r.lo <= r.hi);
            try testing.expect(r.hi <= 0x10FFFF);
            if (prev_hi) |p| {
                // Strictly greater than `p + 1`: equal would mean the
                // generator failed to coalesce two abutting ranges.
                try testing.expect(r.lo > p + 1);
            }
            prev_hi = r.hi;
        }
    }
}

test "XID_Start is a subset of XID_Continue" {
    // Spot-check the containment the generator asserts, from the Zig
    // side, at every table boundary rather than every codepoint.
    for (tables.xid_start) |r| {
        try testing.expect(isXidContinue(r.lo));
        try testing.expect(isXidContinue(r.hi));
    }
}

test "ASCII boundaries" {
    // Letters start; digits only continue; `_` continues but does not
    // start (the formula grammar adds it back — that union is the
    // tokenizer's, not this module's).
    try testing.expect(isXidStart('A'));
    try testing.expect(isXidStart('Z'));
    try testing.expect(isXidStart('a'));
    try testing.expect(isXidStart('z'));
    try testing.expect(!isXidStart('0'));
    try testing.expect(!isXidStart('9'));
    try testing.expect(!isXidStart('_'));
    try testing.expect(!isXidStart('\\'));
    try testing.expect(!isXidStart('$'));
    try testing.expect(!isXidStart('.'));
    try testing.expect(!isXidStart('?'));
    try testing.expect(!isXidStart(' '));

    try testing.expect(isXidContinue('A'));
    try testing.expect(isXidContinue('0'));
    try testing.expect(isXidContinue('9'));
    try testing.expect(isXidContinue('_'));
    try testing.expect(!isXidContinue('.'));
    try testing.expect(!isXidContinue('?'));
    try testing.expect(!isXidContinue('\\'));
    try testing.expect(!isXidContinue('$'));
    try testing.expect(!isXidContinue('-'));
}

test "non-ASCII letters" {
    try testing.expect(isXidStart(0x00C9)); // É
    try testing.expect(isXidStart(0x00DF)); // ß
    try testing.expect(isXidStart(0x03A9)); // Ω GREEK CAPITAL OMEGA
    try testing.expect(isXidStart(0x0414)); // Д CYRILLIC CAPITAL DE
    try testing.expect(isXidStart(0x4E00)); // 一 CJK
    try testing.expect(isXidStart(0x05D0)); // א HEBREW ALEF
    try testing.expect(isXidStart(0x0627)); // ا ARABIC ALEF

    // Excluded: currency, punctuation, symbols, format controls.
    try testing.expect(!isXidStart(0x00A9)); // ©
    try testing.expect(!isXidStart(0x20AC)); // €
    try testing.expect(!isXidStart(0x2212)); // − MINUS SIGN
    try testing.expect(!isXidContinue(0x00A0)); // NBSP
    try testing.expect(!isXidContinue(0x200B)); // ZERO WIDTH SPACE
}

test "combining marks continue but do not start" {
    try testing.expect(!isXidStart(0x0301)); // COMBINING ACUTE ACCENT
    try testing.expect(isXidContinue(0x0301));
    try testing.expect(!isXidStart(0x0324)); // COMBINING DIAERESIS BELOW
    try testing.expect(isXidContinue(0x0324));
    try testing.expect(!isXidStart(0x093C)); // DEVANAGARI SIGN NUKTA
    try testing.expect(isXidContinue(0x093C));
}

test "astral codepoints" {
    try testing.expect(isXidStart(0x10000)); // LINEAR B SYLLABLE B008 A
    try testing.expect(isXidStart(0x1D400)); // 𝐀 MATHEMATICAL BOLD CAPITAL A
    try testing.expect(isXidStart(0x20000)); // CJK ext B
    try testing.expect(isXidContinue(0x1D400));
    try testing.expect(isXidContinue(0x1D165)); // MUSICAL SYMBOL COMBINING STEM

    // Emoji are symbols, not identifier characters.
    try testing.expect(!isXidStart(0x1F600)); // 😀
    try testing.expect(!isXidContinue(0x1F600));
    // Beyond the last assigned plane.
    try testing.expect(!isXidStart(0x10FFFF));
    try testing.expect(!isXidContinue(0x10FFFF));
}

test "surrogate and noncharacter codepoints are excluded" {
    // Surrogates are not scalar values; the tokenizer can never decode
    // one from valid UTF-8, but the predicate must still answer false.
    try testing.expect(!isXidStart(0xD800));
    try testing.expect(!isXidContinue(0xDFFF));
    try testing.expect(!isXidStart(0xFFFE));
    try testing.expect(!isXidContinue(0xFFFF));
}

test "binary search agrees with a linear scan across the whole space" {
    // The search is the only non-generated logic here; sweep every
    // codepoint against a linear membership test so an off-by-one in
    // the probe loop cannot hide behind hand-picked cases.
    var cp: u21 = 0;
    while (cp <= 0x10FFFF) : (cp += 1) {
        try testing.expectEqual(linearMember(tables.xid_start, cp), isXidStart(cp));
        try testing.expectEqual(linearMember(tables.xid_continue, cp), isXidContinue(cp));
    }
}

fn linearMember(ranges: []const tables.Range, cp: u21) bool {
    for (ranges) |r| {
        if (cp >= r.lo and cp <= r.hi) return true;
    }
    return false;
}
