//! A1 phase-1: Unicode case folding for Excel sheet-name dedup.
//!
//! Implements **non-Turkic full case folding** (Unicode statuses C+F)
//! over UTF-8. The fold tables are vendored at
//! `src/unicode/tables/casefold_data.zig`, generated by
//! `scripts/gen_unicode_tables.py` from `CaseFolding.txt`.
//!
//! Two entry points:
//!
//!   - `foldString(allocator, name) ![]u8`
//!     Returns a freshly-allocated UTF-8 string with every codepoint
//!     replaced by its full case-fold mapping. ASCII-only inputs hit
//!     a byte-wise lower-case fast path (no Unicode table lookups).
//!
//!   - `eqlFolded(allocator, a, b) !bool`
//!     Convenience equality test. ASCII-only inputs short-circuit on
//!     length mismatch then byte-wise compare. Mixed UTF-8 falls
//!     through to two `foldString` calls + `mem.eql`.
//!
//! Out-of-scope for this phase: NFC normalisation (lands in
//! `src/unicode/nfc.zig`), char-length validation
//! (`excelSheetNameLength`), and the writer/editor `asciiEqlFold`
//! call-site replacement. Each of those is a separate milestone in
//! the A1 plan; this module ships the foundation.

const std = @import("std");
const tables = @import("tables/casefold_data.zig");
const nfc = @import("nfc.zig");

/// Fully fold a UTF-8 string using non-Turkic full case folding.
/// Returns owned bytes — caller frees.
///
/// Invalid UTF-8 returns `error.InvalidUtf8`.
pub fn foldString(allocator: std.mem.Allocator, input: []const u8) ![]u8 {
    if (isAscii(input)) {
        return foldAscii(allocator, input);
    }
    return foldUtf8(allocator, input);
}

/// True iff `a` and `b` are equal under full case folding.
pub fn eqlFolded(allocator: std.mem.Allocator, a: []const u8, b: []const u8) !bool {
    // Fast path: both ASCII → byte-wise lowercase compare without
    // allocating scratch buffers.
    if (isAscii(a) and isAscii(b)) {
        if (a.len != b.len) return false;
        for (a, b) |ca, cb| {
            if (asciiLower(ca) != asciiLower(cb)) return false;
        }
        return true;
    }
    // General path: fold both, compare. Tolerates one being ASCII —
    // foldString picks the right strategy per-side.
    const fa = try foldString(allocator, a);
    defer allocator.free(fa);
    const fb = try foldString(allocator, b);
    defer allocator.free(fb);
    return std.mem.eql(u8, fa, fb);
}

// ─── Excel sheet-name API (no allocator required) ────────────────────

/// Stack-bounded equality check for Excel sheet names. Excel caps
/// sheet names at 31 scalars, so worst-case input + folded + NFC'd
/// scratch fits comfortably in 2 KiB. Returns false on any
/// allocation / UTF-8 / scratch-overflow error — the only
/// legitimate use is dedup, where "I can't fold this safely"
/// should mean "treat as distinct" rather than fail-loud.
///
/// Pipeline: `NFC(casefold(name))`. NFC handles composed-vs-
/// decomposed equivalents (e.g. `café` precomposed vs
/// `cafe + combining-acute`); casefold handles case-insensitivity.
/// Pure ASCII fast-paths through both layers.
pub fn excelSheetNameEql(a: []const u8, b: []const u8) bool {
    // ASCII fast path: skip both folds entirely.
    if (isAscii(a) and isAscii(b)) {
        if (a.len != b.len) return false;
        for (a, b) |ca, cb| {
            if (asciiLower(ca) != asciiLower(cb)) return false;
        }
        return true;
    }
    // 4 KiB scratch covers the worst-case for two 31-scalar Excel
    // sheet names: each scalar ≤4 bytes UTF-8, full-fold can expand
    // up to ~3× (e.g. ﬃ U+FB03 → "ffi" at 3:1, plus several
    // case-folds with 2-3 byte expansions), and NFC adds a parallel
    // u21 buffer. Worst-case proof: 31 scalars × 4 bytes input ×
    // 3× fold-expansion × 2 (NFC) ≈ 750 B per side; two sides plus
    // u21 ArrayLists (~500 B each) ≈ 2.5 KiB. The previous 2 KiB
    // bound was too tight on max-length adversarial inputs and
    // would silently break the dedup-distinct invariant via the
    // `catch return false` swallow above.
    var buf: [4096]u8 = undefined;
    var fba = std.heap.FixedBufferAllocator.init(&buf);
    const alloc = fba.allocator();
    const fa = foldString(alloc, a) catch return false;
    const fb = foldString(alloc, b) catch return false;
    const na = nfc.normalize(alloc, fa) catch return false;
    const nb = nfc.normalize(alloc, fb) catch return false;
    return std.mem.eql(u8, na, nb);
}

/// Count Unicode scalar values in a UTF-8 string. Used to enforce
/// Excel's 31-character (NOT 31-byte) sheet-name limit.
/// `error.InvalidUtf8` on malformed input.
pub fn excelSheetNameLength(name: []const u8) !usize {
    var i: usize = 0;
    var count: usize = 0;
    while (i < name.len) {
        const seq_len = std.unicode.utf8ByteSequenceLength(name[i]) catch
            return error.InvalidUtf8;
        if (i + seq_len > name.len) return error.InvalidUtf8;
        _ = std.unicode.utf8Decode(name[i .. i + seq_len]) catch
            return error.InvalidUtf8;
        i += seq_len;
        count += 1;
    }
    return count;
}

// ─── ASCII fast path ──────────────────────────────────────────────────

inline fn isAscii(s: []const u8) bool {
    for (s) |c| {
        if (c >= 0x80) return false;
    }
    return true;
}

inline fn asciiLower(c: u8) u8 {
    return if (c >= 'A' and c <= 'Z') c + 32 else c;
}

fn foldAscii(allocator: std.mem.Allocator, input: []const u8) ![]u8 {
    const out = try allocator.alloc(u8, input.len);
    for (input, 0..) |c, i| out[i] = asciiLower(c);
    return out;
}

// ─── Full UTF-8 path ──────────────────────────────────────────────────

fn foldUtf8(allocator: std.mem.Allocator, input: []const u8) ![]u8 {
    // Validate up front so the rest of the loop can trust each
    // sequence — std.unicode.utf8Decode is total when the slice is
    // pre-validated.
    if (!std.unicode.utf8ValidateSlice(input)) return error.InvalidUtf8;

    var out = std.ArrayListUnmanaged(u8){};
    errdefer out.deinit(allocator);
    // Worst-case growth: ß (0xC3 0x9F, 2 bytes) folds to "ss" (2 bytes).
    // Most Latin folds are 1:1 in length; a 2× safety margin is plenty.
    try out.ensureTotalCapacity(allocator, input.len * 2);

    var i: usize = 0;
    while (i < input.len) {
        const seq_len = std.unicode.utf8ByteSequenceLength(input[i]) catch unreachable;
        const cp = std.unicode.utf8Decode(input[i .. i + seq_len]) catch unreachable;
        if (lookupFold(cp)) |mapping| {
            for (mapping) |m| try appendCodepoint(allocator, &out, m);
        } else {
            // No fold entry — copy the source bytes verbatim.
            try out.appendSlice(allocator, input[i .. i + seq_len]);
        }
        i += seq_len;
    }

    return out.toOwnedSlice(allocator);
}

/// Encode a codepoint as UTF-8 and append to `out`. `out` may
/// grow via the allocator — the previous comment claimed callers
/// pre-reserved 4 bytes, but in fact the appendSlice below handles
/// growth itself. The 4-byte stack buffer is the per-call scratch,
/// not a precondition on `out`.
fn appendCodepoint(allocator: std.mem.Allocator, out: *std.ArrayListUnmanaged(u8), cp: u21) !void {
    var buf: [4]u8 = undefined;
    const n = std.unicode.utf8Encode(cp, &buf) catch return error.InvalidUtf8;
    try out.appendSlice(allocator, buf[0..n]);
}

/// Binary search the sorted `fold_entries` table for `cp`. Returns
/// the slice of fold scalars or null if no fold mapping.
fn lookupFold(cp: u21) ?[]const u21 {
    const entries = tables.fold_entries;
    var lo: usize = 0;
    var hi: usize = entries.len;
    while (lo < hi) {
        const mid = lo + (hi - lo) / 2;
        const e = entries[mid];
        if (e.from < cp) {
            lo = mid + 1;
        } else if (e.from > cp) {
            hi = mid;
        } else {
            return tables.fold_scalars[e.offset .. e.offset + e.len];
        }
    }
    return null;
}

// ─── Tests ────────────────────────────────────────────────────────────

test "ASCII fast path: simple uppercase to lowercase" {
    const out = try foldString(std.testing.allocator, "ABC");
    defer std.testing.allocator.free(out);
    try std.testing.expectEqualStrings("abc", out);
}

test "ASCII fast path: lowercase pass-through" {
    const out = try foldString(std.testing.allocator, "abc");
    defer std.testing.allocator.free(out);
    try std.testing.expectEqualStrings("abc", out);
}

test "ASCII fast path: mixed digits + symbols" {
    const out = try foldString(std.testing.allocator, "Hello, World! 123");
    defer std.testing.allocator.free(out);
    try std.testing.expectEqualStrings("hello, world! 123", out);
}

test "Unicode: café → café (lowercase, both NFC)" {
    const out = try foldString(std.testing.allocator, "café");
    defer std.testing.allocator.free(out);
    try std.testing.expectEqualStrings("café", out);
}

test "Unicode: CAFÉ → café" {
    const out = try foldString(std.testing.allocator, "CAFÉ");
    defer std.testing.allocator.free(out);
    try std.testing.expectEqualStrings("café", out);
}

test "Unicode: ß → ss (full fold, status F)" {
    const out = try foldString(std.testing.allocator, "ß");
    defer std.testing.allocator.free(out);
    try std.testing.expectEqualStrings("ss", out);
}

test "Unicode: Σ → σ (Greek capital → small)" {
    const out = try foldString(std.testing.allocator, "Σ");
    defer std.testing.allocator.free(out);
    try std.testing.expectEqualStrings("σ", out);
}

test "Unicode: ς (final sigma) → σ" {
    // Final sigma case-folds to plain sigma per status C in
    // CaseFolding.txt, so Σ/σ/ς all collapse to the same key.
    const out = try foldString(std.testing.allocator, "ς");
    defer std.testing.allocator.free(out);
    try std.testing.expectEqualStrings("σ", out);
}

test "Unicode: Kelvin sign U+212A → k" {
    // U+212A KELVIN SIGN folds to plain ASCII "k". The previous
    // version of this test used ASCII 'K' (U+004B), which would
    // pass via the ASCII fast path and never exercise the table
    // entry for U+212A.
    const out = try foldString(std.testing.allocator, "\u{212A}");
    defer std.testing.allocator.free(out);
    try std.testing.expectEqualStrings("k", out);
}

test "Unicode: Turkish dotted I → still i (non-Turkic policy)" {
    // U+0130 LATIN CAPITAL LETTER I WITH DOT ABOVE folds to "i\u{307}"
    // under non-Turkic full fold (status F). Under Turkic ('T') it
    // would fold to plain "i" — we deliberately do NOT include 'T'.
    const out = try foldString(std.testing.allocator, "İ");
    defer std.testing.allocator.free(out);
    try std.testing.expectEqualStrings("i\u{307}", out);
}

test "Invalid UTF-8 surfaces error.InvalidUtf8" {
    try std.testing.expectError(
        error.InvalidUtf8,
        foldString(std.testing.allocator, "\xFFx"),
    );
}

test "eqlFolded: ASCII case-insensitive match" {
    try std.testing.expect(try eqlFolded(std.testing.allocator, "Sheet1", "SHEET1"));
    try std.testing.expect(!(try eqlFolded(std.testing.allocator, "Sheet1", "Sheet2")));
}

test "eqlFolded: café / CAFÉ" {
    try std.testing.expect(try eqlFolded(std.testing.allocator, "café", "CAFÉ"));
}

test "eqlFolded: ß equals SS" {
    // Empirical Excel matrix item: ß and SS treated as duplicates
    // under full case fold.
    try std.testing.expect(try eqlFolded(std.testing.allocator, "ß", "SS"));
    try std.testing.expect(try eqlFolded(std.testing.allocator, "ß", "ss"));
    try std.testing.expect(try eqlFolded(std.testing.allocator, "Straße", "STRASSE"));
}

test "eqlFolded: distinct strings still distinct" {
    try std.testing.expect(!(try eqlFolded(std.testing.allocator, "café", "cafe")));
    try std.testing.expect(!(try eqlFolded(std.testing.allocator, "Σ", "Π")));
}

test "eqlFolded: length mismatch fast-fails on ASCII path" {
    try std.testing.expect(!(try eqlFolded(std.testing.allocator, "abc", "abcd")));
}

test "Unicode version pinned" {
    // Cheap drift detector — bump when generation script is re-run
    // against a newer UCD.
    try std.testing.expectEqualStrings("17.0.0", tables.unicode_version);
}

test "excelSheetNameEql: ASCII + Unicode duplicate matrix" {
    // ASCII path
    try std.testing.expect(excelSheetNameEql("Sheet1", "SHEET1"));
    try std.testing.expect(!excelSheetNameEql("Sheet1", "Sheet2"));
    // Unicode path
    try std.testing.expect(excelSheetNameEql("café", "CAFÉ"));
    try std.testing.expect(excelSheetNameEql("ß", "SS"));
    try std.testing.expect(excelSheetNameEql("Straße", "STRASSE"));
    try std.testing.expect(excelSheetNameEql("\u{212A}", "k"));
    try std.testing.expect(!excelSheetNameEql("café", "cafe"));
}

test "excelSheetNameLength: counts Unicode scalars not bytes" {
    try std.testing.expectEqual(@as(usize, 6), try excelSheetNameLength("Sheet1"));
    // "café" is 4 scalars (5 bytes — é = 2 bytes UTF-8).
    try std.testing.expectEqual(@as(usize, 4), try excelSheetNameLength("café"));
    // "Straße" is 6 scalars (7 bytes).
    try std.testing.expectEqual(@as(usize, 6), try excelSheetNameLength("Straße"));
    // 31 scalars × 2 bytes each = 62-byte string at exactly the
    // sheet-name length cap.
    var buf: [62]u8 = undefined;
    for (0..31) |i| {
        buf[i * 2] = 0xC3;
        buf[i * 2 + 1] = 0xA9; // é
    }
    try std.testing.expectEqual(@as(usize, 31), try excelSheetNameLength(&buf));
}

test "excelSheetNameLength: rejects malformed UTF-8" {
    try std.testing.expectError(error.InvalidUtf8, excelSheetNameLength("ab\xFFc"));
    try std.testing.expectError(error.InvalidUtf8, excelSheetNameLength("\xC3"));
}
