#!/usr/bin/env python3
"""
A1 (post-0.2.9 roadmap): Unicode table generator.

Reads `CaseFolding.txt` from the Unicode Character Database and
emits a vendored Zig data file that powers `src/unicode/casefold.zig`.

Policy: **non-Turkic full case fold**. Includes status `C` (common /
simple) and `F` (full); excludes `S` (simple-only alternative) and
`T` (Turkic).

Usage:
    scripts/gen_unicode_tables.py \\
        --input /path/to/CaseFolding.txt \\
        --output src/unicode/tables/casefold_data.zig

Output schema (target file):
    pub const unicode_version = "17.0.0";
    pub const FoldEntry = struct { from: u21, len: u8, offset: u32 };
    pub const fold_entries: []const FoldEntry = &.{...};   // sorted by `.from`
    pub const fold_scalars: []const u21 = &.{...};         // pool

Each `FoldEntry` says: codepoint `from` folds to the slice
`fold_scalars[offset..offset+len]`. Entries are sorted by `from` so
runtime lookup is binary-search O(log N).

Tests + build: emit alongside a .zon manifest with the source URL
and SHA-256 of the input so the generation is reproducible.
"""
from __future__ import annotations

import argparse
import hashlib
import re
import sys
from pathlib import Path


CASEFOLD_LINE = re.compile(
    r"^(?P<code>[0-9A-F]+);\s*"
    r"(?P<status>[CFST]);\s*"
    r"(?P<mapping>[0-9A-F ]+);\s*#"
)

VERSION_LINE = re.compile(r"^# CaseFolding-(?P<version>[0-9.]+)\.txt")


def parse_input(path: Path) -> tuple[str, list[tuple[int, list[int]]]]:
    """Parse CaseFolding.txt; return (unicode_version, [(from, [to])])
    keeping only statuses 'C' and 'F' (non-Turkic full case fold)."""
    version = ""
    entries: list[tuple[int, list[int]]] = []
    with path.open() as f:
        for line in f:
            if not version:
                m = VERSION_LINE.match(line)
                if m:
                    version = m.group("version")
            m = CASEFOLD_LINE.match(line)
            if not m:
                continue
            status = m.group("status")
            if status not in ("C", "F"):
                # Skip simple-only ('S') — full ('F') already covers
                # the same source codepoints with a richer mapping.
                # Skip Turkic ('T') per the non-Turkic policy choice.
                continue
            src = int(m.group("code"), 16)
            mapping = [int(c, 16) for c in m.group("mapping").split()]
            entries.append((src, mapping))
    if not version:
        raise SystemExit("gen_unicode_tables: input missing # CaseFolding-X.Y.Z.txt header")
    # Sort by source codepoint (already sorted in UCD but be defensive).
    entries.sort(key=lambda e: e[0])
    # Sanity: no duplicate sources.
    seen = set()
    for src, _ in entries:
        if src in seen:
            raise SystemExit(f"gen_unicode_tables: duplicate source codepoint U+{src:04X}")
        seen.add(src)
    return version, entries


def emit_zig(
    out_path: Path, version: str, entries: list[tuple[int, list[int]]], input_sha256: str
) -> None:
    """Render the generated Zig file."""
    # Build the scalar pool: concatenate all mappings, indexed by offset.
    pool: list[int] = []
    fold_records: list[tuple[int, int, int]] = []  # (from, len, offset)
    for src, mapping in entries:
        offset = len(pool)
        pool.extend(mapping)
        fold_records.append((src, len(mapping), offset))

    lines = [
        "// AUTO-GENERATED by scripts/gen_unicode_tables.py — DO NOT EDIT",
        "// Source: https://www.unicode.org/Public/UCD/latest/ucd/CaseFolding.txt",
        f"// SHA-256 of input: {input_sha256}",
        f"// Unicode version: {version}",
        "// Policy: non-Turkic full case fold (statuses C + F).",
        "",
        f'pub const unicode_version: []const u8 = "{version}";',
        "",
        "pub const FoldEntry = struct {",
        "    from: u21,",
        "    len: u8,",
        "    offset: u32,",
        "};",
        "",
        "pub const fold_entries: []const FoldEntry = &.{",
    ]
    for src, length, offset in fold_records:
        lines.append(f"    .{{ .from = 0x{src:04X}, .len = {length}, .offset = {offset} }},")
    lines.append("};")
    lines.append("")
    lines.append("pub const fold_scalars: []const u21 = &.{")
    # Pack 8 codepoints per line for readability + smaller diff churn.
    for i in range(0, len(pool), 8):
        chunk = ", ".join(f"0x{c:04X}" for c in pool[i : i + 8])
        lines.append(f"    {chunk},")
    lines.append("};")
    lines.append("")

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines))
    print(f"gen_unicode_tables: {len(entries)} entries, {len(pool)} pool scalars → {out_path}")


def main() -> int:
    p = argparse.ArgumentParser()
    p.add_argument("--input", type=Path, required=True, help="Path to CaseFolding.txt")
    p.add_argument("--output", type=Path, required=True, help="Path to generated .zig file")
    args = p.parse_args()

    raw = args.input.read_bytes()
    digest = hashlib.sha256(raw).hexdigest()
    version, entries = parse_input(args.input)
    emit_zig(args.output, version, entries, digest)
    return 0


if __name__ == "__main__":
    sys.exit(main())
