#!/usr/bin/env bash
# THE reviewed regeneration command for the oracle fixtures
# (M1b, goal_formula.md §8.2: "Regeneration = reviewed command +
# manifest diff").
#
# There is exactly one way to regenerate a golden, and this is it. That
# matters more than it sounds: a golden regenerated by an ad-hoc command
# somebody ran once is indistinguishable, in the diff, from a golden
# regenerated correctly — and the whole value of an oracle is that its
# numbers came from a process you can re-run and argue with.
#
# What it does, in order:
#   1. rebuild the input workbooks (deterministic — same bytes every time)
#   2. rebuild the hand-derived manifests
#   3. run each available application leg
#   4. record each run through the sentinel gate; a run that cannot prove
#      it recalculated is REFUSED and writes nothing
#   5. show the manifest diff and stop, WITHOUT committing anything
#
# Step 5 is the "reviewed" part. This script never writes to the
# fixtures directory behind your back: it stages into a temporary tree,
# diffs against what is committed, and leaves the decision to a human.
# Pass --apply once you have read the diff.
#
# Usage:
#   scripts/oracle/regenerate.sh            # rebuild, diff, do not touch fixtures
#   scripts/oracle/regenerate.sh --apply    # …and copy the result in

set -euo pipefail

repo_root=$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)
cd "$repo_root"

apply=0
[ "${1:-}" = "--apply" ] && apply=1

fixtures="tests/oracle/fixtures"
inputs="tests/oracle/inputs"
staging=$(mktemp -d)
trap 'rm -rf "$staging"' EXIT

recorder="zig-out/bin/zlsx-oracle-record"
if [ ! -x "$recorder" ]; then
  echo "==> building the recorder"
  zig build
fi

# ─── 1. inputs ───────────────────────────────────────────────────

echo "==> rebuilding input workbooks"
python3 scripts/oracle/build_inputs.py --out "$staging/inputs"

# The inputs are committed, and `build_inputs.py` is deterministic
# (fixed timestamps, fixed part order), so a difference here means the
# builder changed. That invalidates every provenance digest recorded
# against the old bytes, which is exactly the kind of silent staleness
# the digest exists to catch — so say so loudly.
inputs_changed=0
for f in "$staging/inputs"/*.xlsx; do
  name=$(basename "$f")
  if [ ! -f "$inputs/$name" ] || ! cmp -s "$f" "$inputs/$name"; then
    inputs_changed=1
    echo "    input CHANGED: $name"
  fi
done
if [ "$inputs_changed" = 1 ]; then
  cat <<'EOF'

    The input workbooks differ from what is committed. Every provenance
    record pins the digest of the workbook its values came from, so all
    existing manifests are now recorded against inputs that no longer
    exist. Re-run every leg — a partial regeneration would leave
    manifests that cannot be compared with each other.

EOF
fi

# ─── 2. hand-derived manifests ───────────────────────────────────

echo "==> rebuilding hand-derived manifests"
python3 scripts/oracle/build_hand_spec.py \
  --input "$staging/inputs/oracle_suite.xlsx" \
  --out "$staging/fixtures"

# ─── 3+4. application legs ───────────────────────────────────────

run_leg() {
  local leg="$1" driver="$2" fidelity="$3"
  echo "==> $leg"
  local recalculated="$staging/$leg.xlsx"

  local rc=0
  bash "$driver" "$staging/inputs/oracle_suite.xlsx" "$recalculated" || rc=$?
  if [ "$rc" = 3 ]; then
    echo "    PARKED — leg skipped, existing fixture left untouched"
    # Carry the committed manifest forward so the diff shows only what
    # actually changed, rather than reporting a parked leg as a deletion.
    if [ -f "$fixtures/${leg}_oracle_suite.json" ]; then
      cp "$fixtures/${leg}_oracle_suite.json" "$staging/fixtures/"
    fi
    return 0
  fi
  if [ "$rc" != 0 ]; then
    echo "    FAILED (exit $rc)" >&2
    return 1
  fi

  # The sentinel gate lives inside the recorder: a run that cannot prove
  # it recalculated exits 2 and writes nothing.
  local out="$staging/fixtures/${leg}_oracle_suite.json"
  local prov="${recalculated%.xlsx}.provenance.json"
  if ! "$recorder" "$recalculated" "$prov" oracle_suite "$fidelity" "$out"; then
    echo "    REFUSED — the run did not prove it recalculated; no manifest written" >&2
    return 1
  fi
}

run_leg libreoffice scripts/oracle/record_libreoffice.sh excel
run_leg excel_mac scripts/oracle/record_excel_mac.sh excel

# ─── 5. the diff ─────────────────────────────────────────────────

echo
echo "==> manifest diff (committed → regenerated)"
if diff -ru "$fixtures" "$staging/fixtures" >"$staging/manifest.diff" 2>&1; then
  echo "    no changes"
else
  cat "$staging/manifest.diff"

  # Classify the diff, because an application leg's `workbook_digest`
  # changes on EVERY run: Excel and LibreOffice both embed
  # non-deterministic bytes (timestamps, document ids) when they save,
  # so the recalculated file is never byte-identical even when every
  # value in it is. Saying so here is what keeps the review meaningful —
  # otherwise reviewers learn to skim past a diff that is usually noise
  # and one day is not.
  changed_lines=$(grep -cE '^[+-][^+-]' "$staging/manifest.diff" || true)
  digest_lines=$(grep -cE '^[+-].*"workbook_digest"' "$staging/manifest.diff" || true)
  echo
  if [ "$changed_lines" = "$digest_lines" ] && [ "$digest_lines" != "0" ]; then
    echo "    DIGEST ONLY — no recorded value changed."
    echo "    Applications embed a timestamp on save, so this is expected."
  else
    echo "    $((changed_lines - digest_lines)) non-digest line(s) changed:"
    echo "    a recorded value, an exclusion, or a provenance field moved."
    echo "    Read those before applying — that is the divergence."
  fi
fi

echo
if [ "$apply" = 1 ]; then
  mkdir -p "$fixtures" "$inputs"
  cp "$staging/fixtures"/*.json "$fixtures/"
  cp "$staging/inputs"/*.xlsx "$inputs/"
  echo '==> applied. Review "git diff" before committing.'
else
  echo "==> NOT applied. Read the diff above, then re-run with --apply."
fi
