//! Greenfield drawing emit (B1 iter-wb-c2b, minimal).
//!
//! Scope of v1: a single image, anchored at one cell (top-left), zero
//! pixel offset, fixed 1-inch × 1-inch extent. Sheets that already
//! carry a `<drawing>` element are rejected with
//! `error.SheetHasExistingDrawing`. Range-anchor, pixel offsets, and
//! native-size extent come in follow-up iters.
//!
//! Per OOXML spec (Part 1, Annex A) emitting a single image into a
//! drawing-less sheet requires touching FIVE artifacts:
//!
//!   1. `xl/media/imageN.{ext}`           — image bytes (STORED).
//!   2. `xl/drawings/drawingN.xml`        — wsDr/oneCellAnchor wrapper.
//!   3. `xl/drawings/_rels/drawingN.xml.rels` — drawing → image link.
//!   4. `xl/worksheets/sheetN.xml`        — append `<drawing r:id=...>`.
//!   5. `xl/worksheets/_rels/sheetN.xml.rels` — sheet → drawing link.
//!
//! `PartStore.addPart` registers content types via the
//! `<Override>` mechanism; the image content type (`image/png` etc.)
//! is added the same way (the Office consumers we care about accept
//! per-image overrides over the `<Default Extension="png">` form, so
//! we don't need to touch the Defaults block).

const std = @import("std");
const assert = std.debug.assert;

const store_mod = @import("store.zig");
const PartStore = store_mod.PartStore;

pub const ImageMime = enum {
    png,
    jpeg,
    gif,

    pub fn contentType(self: ImageMime) []const u8 {
        return switch (self) {
            .png => "image/png",
            .jpeg => "image/jpeg",
            .gif => "image/gif",
        };
    }

    pub fn extension(self: ImageMime) []const u8 {
        return switch (self) {
            .png => "png",
            .jpeg => "jpg",
            .gif => "gif",
        };
    }
};

pub const Error = error{
    /// `bytes` magic header didn't match `mime`.
    MimeMagicMismatch,
    /// `cell_anchor` carried a 0 row or 0 col (OOXML is 1-based).
    InvalidAnchor,
    /// Target sheet already has a `<drawing>` element. Multi-image
    /// support against existing drawings is out of scope for v1.
    SheetHasExistingDrawing,
    /// `bytes` was empty.
    EmptyImage,
};

/// 1-based (col, row), matching OOXML A1 conventions. Distinct from
/// `Workbook.CellRef` (which is row-major) because the only call site
/// is image anchoring and the OOXML drawing wire format puts col
/// first.
pub const ImageCellAnchor = struct {
    col: u32,
    row: u32,
};

/// Validate the magic header for `mime` against the leading bytes of
/// `bytes`. Defensive: callers pass a declared MIME plus a byte
/// buffer; if the two disagree, the resulting xlsx will look fine in
/// the package metadata but Office may render a broken-image
/// placeholder. Cheaper to reject up front.
pub fn validateMagic(mime: ImageMime, bytes: []const u8) Error!void {
    if (bytes.len == 0) return Error.EmptyImage;
    switch (mime) {
        .png => {
            // 89 50 4E 47 0D 0A 1A 0A
            const sig = [_]u8{ 0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A };
            if (bytes.len < sig.len) return Error.MimeMagicMismatch;
            if (!std.mem.eql(u8, bytes[0..sig.len], &sig)) return Error.MimeMagicMismatch;
        },
        .jpeg => {
            // FF D8 FF
            if (bytes.len < 3) return Error.MimeMagicMismatch;
            if (bytes[0] != 0xFF or bytes[1] != 0xD8 or bytes[2] != 0xFF) {
                return Error.MimeMagicMismatch;
            }
        },
        .gif => {
            // 47 49 46 (GIF)
            if (bytes.len < 3) return Error.MimeMagicMismatch;
            if (bytes[0] != 'G' or bytes[1] != 'I' or bytes[2] != 'F') {
                return Error.MimeMagicMismatch;
            }
        },
    }
}

/// Walk every part name in the store and return the lowest unused
/// `<prefix>N<suffix>` integer >= 1. Used for `imageN.png`,
/// `drawingN.xml` etc. — the OOXML convention for autogenerated
/// part names. We don't try to be clever about gap-filling: bumping
/// past the highest seen N keeps the result stable across saves.
pub fn nextFreeNumber(
    store: *const PartStore,
    prefix: []const u8,
    suffix: []const u8,
) u32 {
    assert(prefix.len > 0);
    var max_seen: u32 = 0;
    for (store.parts) |p| {
        if (!std.mem.startsWith(u8, p.name, prefix)) continue;
        if (!std.mem.endsWith(u8, p.name, suffix)) continue;
        const middle = p.name[prefix.len .. p.name.len - suffix.len];
        const n = std.fmt.parseInt(u32, middle, 10) catch continue;
        if (n > max_seen) max_seen = n;
    }
    return max_seen + 1;
}

/// Build the drawingN.xml body for a single oneCellAnchor image
/// pinned at `(col-1, row-1)` with zero pixel offset and a fixed
/// 1-inch × 1-inch extent (914 400 EMU per inch).
pub fn buildDrawingXml(
    allocator: std.mem.Allocator,
    anchor: ImageCellAnchor,
) ![]u8 {
    assert(anchor.col >= 1);
    assert(anchor.row >= 1);

    var buf: std.ArrayListUnmanaged(u8) = .empty;
    defer buf.deinit(allocator);

    try buf.appendSlice(allocator, "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>");
    try buf.appendSlice(
        allocator,
        "<xdr:wsDr xmlns:xdr=\"http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing\"" ++
            " xmlns:a=\"http://schemas.openxmlformats.org/drawingml/2006/main\"" ++
            " xmlns:r=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships\">",
    );
    try buf.appendSlice(allocator, "<xdr:oneCellAnchor>");
    try buf.appendSlice(allocator, "<xdr:from>");
    var num_buf: [32]u8 = undefined;
    try buf.appendSlice(allocator, "<xdr:col>");
    try buf.appendSlice(allocator, try std.fmt.bufPrint(&num_buf, "{d}", .{anchor.col - 1}));
    try buf.appendSlice(allocator, "</xdr:col><xdr:colOff>0</xdr:colOff>");
    try buf.appendSlice(allocator, "<xdr:row>");
    try buf.appendSlice(allocator, try std.fmt.bufPrint(&num_buf, "{d}", .{anchor.row - 1}));
    try buf.appendSlice(allocator, "</xdr:row><xdr:rowOff>0</xdr:rowOff>");
    try buf.appendSlice(allocator, "</xdr:from>");
    // 1 inch = 914400 EMU. Fixed for v1.
    try buf.appendSlice(allocator, "<xdr:ext cx=\"914400\" cy=\"914400\"/>");
    try buf.appendSlice(allocator, "<xdr:pic>");
    try buf.appendSlice(
        allocator,
        "<xdr:nvPicPr><xdr:cNvPr id=\"1\" name=\"Picture 1\"/><xdr:cNvPicPr/></xdr:nvPicPr>",
    );
    try buf.appendSlice(
        allocator,
        "<xdr:blipFill><a:blip r:embed=\"rId1\"/><a:stretch><a:fillRect/></a:stretch></xdr:blipFill>",
    );
    try buf.appendSlice(
        allocator,
        "<xdr:spPr><a:prstGeom prst=\"rect\"><a:avLst/></a:prstGeom></xdr:spPr>",
    );
    try buf.appendSlice(allocator, "</xdr:pic>");
    try buf.appendSlice(allocator, "<xdr:clientData/>");
    try buf.appendSlice(allocator, "</xdr:oneCellAnchor>");
    try buf.appendSlice(allocator, "</xdr:wsDr>");

    return try buf.toOwnedSlice(allocator);
}

/// Build the drawing-rels file linking `rId1` to `../media/imageN.{ext}`.
pub fn buildDrawingRels(
    allocator: std.mem.Allocator,
    image_part_basename: []const u8,
) ![]u8 {
    assert(image_part_basename.len > 0);

    var buf: std.ArrayListUnmanaged(u8) = .empty;
    defer buf.deinit(allocator);

    try buf.appendSlice(
        allocator,
        "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>" ++
            "<Relationships xmlns=\"http://schemas.openxmlformats.org/package/2006/relationships\">",
    );
    try buf.appendSlice(allocator, "<Relationship Id=\"rId1\" Type=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships/image\" Target=\"../media/");
    try buf.appendSlice(allocator, image_part_basename);
    try buf.appendSlice(allocator, "\"/>");
    try buf.appendSlice(allocator, "</Relationships>");

    return try buf.toOwnedSlice(allocator);
}

/// Build the bytes for a brand-new `xl/worksheets/_rels/sheetN.xml.rels`
/// containing exactly one Relationship to `../drawings/drawingN.xml`.
pub fn buildFreshSheetRels(
    allocator: std.mem.Allocator,
    drawing_basename: []const u8,
    rel_id: []const u8,
) ![]u8 {
    assert(drawing_basename.len > 0);
    assert(rel_id.len > 0);

    var buf: std.ArrayListUnmanaged(u8) = .empty;
    defer buf.deinit(allocator);

    try buf.appendSlice(
        allocator,
        "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>" ++
            "<Relationships xmlns=\"http://schemas.openxmlformats.org/package/2006/relationships\">",
    );
    try buf.appendSlice(allocator, "<Relationship Id=\"");
    try buf.appendSlice(allocator, rel_id);
    try buf.appendSlice(allocator, "\" Type=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships/drawing\" Target=\"../drawings/");
    try buf.appendSlice(allocator, drawing_basename);
    try buf.appendSlice(allocator, "\"/>");
    try buf.appendSlice(allocator, "</Relationships>");

    return try buf.toOwnedSlice(allocator);
}

/// Splice a `<Relationship>` element into existing rels XML before
/// `</Relationships>`. Caller owns the returned bytes.
pub fn appendRelationship(
    allocator: std.mem.Allocator,
    existing_xml: []const u8,
    drawing_basename: []const u8,
    rel_id: []const u8,
) ![]u8 {
    const close_tag = "</Relationships>";
    const close_pos = std.mem.lastIndexOf(u8, existing_xml, close_tag) orelse
        return error.MalformedSheetRels;

    var buf: std.ArrayListUnmanaged(u8) = .empty;
    defer buf.deinit(allocator);

    try buf.appendSlice(allocator, existing_xml[0..close_pos]);
    try buf.appendSlice(allocator, "<Relationship Id=\"");
    try buf.appendSlice(allocator, rel_id);
    try buf.appendSlice(allocator, "\" Type=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships/drawing\" Target=\"../drawings/");
    try buf.appendSlice(allocator, drawing_basename);
    try buf.appendSlice(allocator, "\"/>");
    try buf.appendSlice(allocator, existing_xml[close_pos..]);

    return try buf.toOwnedSlice(allocator);
}

/// Splice `<drawing r:id="..."/>` into a sheet's XML, immediately
/// before `</worksheet>`. Caller owns the returned bytes.
pub fn appendDrawingElementToSheet(
    allocator: std.mem.Allocator,
    sheet_xml: []const u8,
    rel_id: []const u8,
) ![]u8 {
    assert(rel_id.len > 0);

    const close_tag = "</worksheet>";
    const close_pos = std.mem.lastIndexOf(u8, sheet_xml, close_tag) orelse
        return error.MalformedSheetXml;

    var buf: std.ArrayListUnmanaged(u8) = .empty;
    defer buf.deinit(allocator);

    try buf.appendSlice(allocator, sheet_xml[0..close_pos]);
    // The `r:` namespace prefix is bound in the worksheet root by
    // every OOXML producer we've round-tripped (xmlns:r=...
    // /relationships); we emit it without re-declaring.
    try buf.appendSlice(allocator, "<drawing r:id=\"");
    try buf.appendSlice(allocator, rel_id);
    try buf.appendSlice(allocator, "\"/>");
    try buf.appendSlice(allocator, sheet_xml[close_pos..]);

    return try buf.toOwnedSlice(allocator);
}

/// Pick the next free `rId<N>` for the given existing rels list.
/// Returns the integer N (caller formats `rId<N>`). Stable across
/// saves: bumps past max(N) rather than gap-filling.
pub fn nextFreeRelId(rels: []const store_mod.Relationship) u32 {
    var max_seen: u32 = 0;
    for (rels) |r| {
        if (!std.mem.startsWith(u8, r.id, "rId")) continue;
        const n = std.fmt.parseInt(u32, r.id[3..], 10) catch continue;
        if (n > max_seen) max_seen = n;
    }
    return max_seen + 1;
}

// ─── Tests ────────────────────────────────────────────────────────────

test "validateMagic: PNG accepts canonical 8-byte signature" {
    const png = [_]u8{ 0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A, 0x00 };
    try validateMagic(.png, &png);
}

test "validateMagic: PNG declared with JPEG bytes errors typed" {
    const jpeg = [_]u8{ 0xFF, 0xD8, 0xFF, 0xE0 };
    try std.testing.expectError(Error.MimeMagicMismatch, validateMagic(.png, &jpeg));
}

test "validateMagic: empty bytes errors EmptyImage" {
    try std.testing.expectError(Error.EmptyImage, validateMagic(.png, &.{}));
}

test "validateMagic: JPEG accepts FFD8FF prefix" {
    const jpeg = [_]u8{ 0xFF, 0xD8, 0xFF, 0xE0, 0x00, 0x10 };
    try validateMagic(.jpeg, &jpeg);
}

test "validateMagic: GIF accepts 'GIF' prefix" {
    const gif = "GIF89a\x00\x00";
    try validateMagic(.gif, gif);
}

test "buildDrawingXml: anchors to (col-1, row-1) and emits oneCellAnchor" {
    const xml = try buildDrawingXml(std.testing.allocator, .{ .col = 3, .row = 5 });
    defer std.testing.allocator.free(xml);
    try std.testing.expect(std.mem.indexOf(u8, xml, "<xdr:col>2</xdr:col>") != null);
    try std.testing.expect(std.mem.indexOf(u8, xml, "<xdr:row>4</xdr:row>") != null);
    try std.testing.expect(std.mem.indexOf(u8, xml, "<xdr:oneCellAnchor>") != null);
    try std.testing.expect(std.mem.indexOf(u8, xml, "r:embed=\"rId1\"") != null);
    try std.testing.expect(std.mem.indexOf(u8, xml, "cx=\"914400\"") != null);
}

test "buildDrawingRels: includes ../media/<basename> target" {
    const rels = try buildDrawingRels(std.testing.allocator, "image1.png");
    defer std.testing.allocator.free(rels);
    try std.testing.expect(std.mem.indexOf(u8, rels, "Target=\"../media/image1.png\"") != null);
    try std.testing.expect(std.mem.indexOf(u8, rels, "Id=\"rId1\"") != null);
}

test "appendDrawingElementToSheet: splices before </worksheet>" {
    const sheet =
        "<?xml version=\"1.0\"?>" ++
        "<worksheet xmlns:r=\"...\"><sheetData/></worksheet>";
    const out = try appendDrawingElementToSheet(std.testing.allocator, sheet, "rId7");
    defer std.testing.allocator.free(out);
    try std.testing.expect(std.mem.indexOf(u8, out, "<drawing r:id=\"rId7\"/></worksheet>") != null);
}

test "appendRelationship: appends before </Relationships>" {
    const existing =
        "<?xml version=\"1.0\"?>" ++
        "<Relationships xmlns=\"http://schemas.openxmlformats.org/package/2006/relationships\">" ++
        "<Relationship Id=\"rId1\" Type=\"x\" Target=\"y\"/>" ++
        "</Relationships>";
    const out = try appendRelationship(std.testing.allocator, existing, "drawing1.xml", "rId2");
    defer std.testing.allocator.free(out);
    try std.testing.expect(std.mem.indexOf(u8, out, "Id=\"rId2\"") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "Target=\"../drawings/drawing1.xml\"") != null);
    // Original rel still present.
    try std.testing.expect(std.mem.indexOf(u8, out, "Id=\"rId1\"") != null);
}
